/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sets;
import java.util.HashSet;
import java.util.Objects;

/**
 *
 * @author Farzana
 */
public class BookSetExample {
    int id;
    String name;

    // Two Books are equal if their IDs are equal
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BookSetExample book = (BookSetExample) o;
        return id == book.id;
    }
    //generate hascode 
  //  Simply put, hashCode() returns an integer value, generated by a hashing algorithm.
   @Override
    public int hashCode() {
        return Objects.hash(id);
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BookSetExample(int id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public String toString() {
        return "BookSetExample{" + "id=" + id + ", name=" + name + '}';
    }
    
    
    public static void main(String args[]){
    
    // double element not save for overrite hascode and euqals method
    
    HashSet<BookSetExample> sets=new HashSet<>();
    sets.add(new BookSetExample(0, "networking"));
    sets.add(new BookSetExample(1,"data sturctue "));
    sets.add(new BookSetExample(0, "networking")); 
    
    for(BookSetExample book : sets){
        System.out.println(" "+book.getId()+" "+book.getName());
    }

    }
}
